version: 2
project_name: im-delivery-service

before:
  hooks:
    - go mod tidy

builds:
  - id: delivery-service
    main: ./cmd/main.go
    binary: im-delivery-service
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    
    ldflags:
      - -s -w
      - -X github.com/webitel/im-delivery-service/internal/domain/model.Version={{.Version}}
      - -X github.com/webitel/im-delivery-service/internal/domain/model.Commit={{.FullCommit}}
      - -X github.com/webitel/im-delivery-service/internal/domain/model.CommitDate={{.CommitDate}}
      - -X github.com/webitel/im-delivery-service/internal/domain/model.Branch={{.Branch}}
      - -X github.com/webitel/im-delivery-service/internal/domain/model.BuildTimestamp={{.Date}}
      - -X github.com/webitel/im-delivery-service/internal/domain/model.BuiltBy=github-actions

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64{{ else }}{{ .Arch }}{{ end }}

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'