// Code generated by "stringer -type=EventKind"; DO NOT EDIT.

package event

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Connected-1]
	_ = x[Disconnected-2]
	_ = x[MessageCreated-3]
}

const _EventKind_name = "ConnectedDisconnectedMessageCreated"

var _EventKind_index = [...]uint8{0, 9, 21, 35}

func (i EventKind) String() string {
	i -= 1
	if i < 0 || i >= EventKind(len(_EventKind_index)-1) {
		return "EventKind(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _EventKind_name[_EventKind_index[i]:_EventKind_index[i+1]]
}
