// Code generated by "stringer -type=EventKind"; DO NOT EDIT.

package event

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Connected-1]
	_ = x[DisconnectedEvent-2]
	_ = x[MessageCreated-3]
	_ = x[ThreadCreated-4]
	_ = x[MessageRead-5]
	_ = x[VariableSet-6]
	_ = x[VariableFlush-7]
	_ = x[MemberAdded-8]
	_ = x[MemberLeft-9]
	_ = x[InteractiveCallback-10]
	_ = x[MessageEdited-11]
	_ = x[MessageStatusChanged-12]
	_ = x[MessageDeleted-13]
	_ = x[Typing-14]
	_ = x[MessageReaction-15]
}

const _EventKind_name = "ConnectedDisconnectedEventMessageCreatedThreadCreatedMessageReadVariableSetVariableFlushMemberAddedMemberLeftInteractiveCallbackMessageEditedMessageStatusChangedMessageDeletedTypingMessageReaction"

var _EventKind_index = [...]uint8{0, 9, 26, 40, 53, 64, 75, 88, 99, 109, 128, 141, 161, 175, 181, 196}

func (i EventKind) String() string {
	i -= 1
	if i < 0 || i >= EventKind(len(_EventKind_index)-1) {
		return "EventKind(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _EventKind_name[_EventKind_index[i]:_EventKind_index[i+1]]
}
