// Code generated by "stringer -type=EventPriority -linecomment"; DO NOT EDIT.

package wsmarshaller

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PriorityUnspecified-0]
	_ = x[PriorityHigh-1]
	_ = x[PriorityNormal-2]
	_ = x[PriorityLow-3]
}

const _EventPriority_name = "unspecifiedhighnormallow"

var _EventPriority_index = [...]uint8{0, 11, 15, 21, 24}

func (i EventPriority) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_EventPriority_index)-1 {
		return "EventPriority(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _EventPriority_name[_EventPriority_index[idx]:_EventPriority_index[idx+1]]
}
