// Code generated by "stringer -type=EventType -linecomment"; DO NOT EDIT.

package wsmarshaller

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[EventConnected-0]
	_ = x[EventDisconnected-1]
	_ = x[EventMessage-2]
	_ = x[EventThreadCreated-3]
	_ = x[EventAck-4]
	_ = x[EventError-5]
	_ = x[EventPing-6]
}

const _EventType_name = "connected_eventdisconnected_eventmessage_eventthread_created_eventack_eventerror_eventping_event"

var _EventType_index = [...]uint8{0, 15, 33, 46, 66, 75, 86, 96}

func (i EventType) String() string {
	if i < 0 || i >= EventType(len(_EventType_index)-1) {
		return "EventType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _EventType_name[_EventType_index[i]:_EventType_index[i+1]]
}
