// Code generated by "stringer -type=EventKind"; DO NOT EDIT.

package model

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Connected-1]
}

const _EventKind_name = "Connected"

var _EventKind_index = [...]uint8{0, 9}

func (i InboundEventKind) String() string {
	i -= 1
	if i < 0 || i >= InboundEventKind(len(_EventKind_index)-1) {
		return "EventKind(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _EventKind_name[_EventKind_index[i]:_EventKind_index[i+1]]
}
