// Code generated by "stringer -type=PeerType"; DO NOT EDIT.

package model

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PeerUser-1]
	_ = x[PeerBot-2]
	_ = x[PeerChat-3]
	_ = x[PeerChannel-4]
}

const _PeerType_name = "PeerUserPeerBotPeerChatPeerChannel"

var _PeerType_index = [...]uint8{0, 8, 15, 23, 34}

func (i PeerType) String() string {
	i -= 1
	if i < 0 || i >= PeerType(len(_PeerType_index)-1) {
		return "PeerType(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _PeerType_name[_PeerType_index[i]:_PeerType_index[i+1]]
}
